<?php

declare(strict_types=1);

/**
 * Imports the built prompt packages as PUBLISHED versions (P8.3).
 *
 * Usage (dev): docker compose run --rm php php scripts/import-prompt-packages.php [file.json ...]
 * Default input: every build/prompt-packages/*.json
 *                (generated by: node scripts/build-default-prompt-package.mjs)
 *
 * Each document is validated against schemas/prompt-package.schema.json
 * BEFORE insertion. Idempotent by content hash: re-running with the same
 * content is a no-op (exit 0); a DIFFERENT content under an existing
 * (id, version) is refused (published versions are immutable, exit 1).
 *
 * Production without SSH uses POST /api/admin/import-prompt-package
 * (X-Migrate-Token, same trust model as import-referentiel — ADR-008).
 *
 * Config via env: DB_HOST, DB_NAME, DB_USER, DB_PASSWORD (optional DB_PORT).
 * Exit code 0 on success/no-op, 1 on failure.
 */

$root = dirname(__DIR__);
$autoload = $root . '/api/vendor/autoload.php';
if (!is_file($autoload)) {
    fwrite(STDERR, "Error: composer autoload not found — run: docker compose run --rm php composer install\n");
    exit(1);
}
require $autoload;

use Humanome\Db;
use Humanome\Packages\InvalidPackageException;
use Humanome\Packages\PackageConflictException;
use Humanome\Packages\PromptPackageRepository;

$files = array_slice($argv, 1);
if ($files === []) {
    $files = glob($root . '/build/prompt-packages/*.json') ?: [];
}
if ($files === []) {
    fwrite(STDERR, "Error: no package file found in build/prompt-packages/.\n");
    fwrite(STDERR, "Generate the default package with: node scripts/build-default-prompt-package.mjs\n");
    exit(1);
}

if (!Db::isConfigured()) {
    fwrite(STDERR, "Error: DB_HOST is not set (expected DB_HOST/DB_NAME/DB_USER/DB_PASSWORD in env).\n");
    exit(1);
}

$repository = new PromptPackageRepository(Db::get());
$failed = false;

foreach ($files as $file) {
    if (!is_file($file)) {
        fwrite(STDERR, "Error: package file not found: {$file}\n");
        $failed = true;
        continue;
    }

    try {
        $doc = json_decode((string) file_get_contents($file), true, 512, JSON_THROW_ON_ERROR);
        if (!is_array($doc)) {
            throw new RuntimeException('Top-level JSON value is not an object');
        }
        $result = $repository->importPublishedDocument($doc);
    } catch (InvalidPackageException $e) {
        fwrite(STDERR, 'Invalid prompt-package document ' . basename($file) . ":\n");
        foreach ($e->getErrors() as $pointer => $messages) {
            fwrite(STDERR, sprintf("  %s: %s\n", $pointer, implode(' | ', (array) $messages)));
        }
        $failed = true;
        continue;
    } catch (PackageConflictException $e) {
        fwrite(STDERR, 'Conflict on ' . basename($file) . ': ' . $e->getMessage() . "\n");
        $failed = true;
        continue;
    } catch (Throwable $e) {
        fwrite(STDERR, 'Import failed for ' . basename($file) . ': ' . $e->getMessage() . "\n");
        $failed = true;
        continue;
    }

    printf(
        "%s — %s@%s (hash %s)%s\n",
        $result['status'] === 'unchanged' ? 'already imported' : 'imported as published',
        $result['id'],
        $result['version'],
        substr($result['contentHash'], 0, 12),
        $result['status'] === 'unchanged' ? ', nothing to do' : '',
    );
}

exit($failed ? 1 : 0);
