<?php

declare(strict_types=1);

/**
 * Imports the extracted RESPIRE v7 referentiel as the initial published
 * version of referentiel "respire" (P4.1).
 *
 * Usage (dev): docker compose run --rm php php scripts/import-referentiel.php [file.json]
 * Default input: web/public/data/referentiel/respire-v7.json
 *                (generated by: node scripts/extract-referentiel.mjs)
 *
 * The document is validated against schemas/referentiel.schema.json BEFORE
 * insertion; its contentHash is recomputed and checked. Idempotent:
 * re-running with the same content is a no-op (exit 0).
 *
 * Config via env: DB_HOST, DB_NAME, DB_USER, DB_PASSWORD (optional DB_PORT).
 * Exit code 0 on success/no-op, 1 on failure.
 */

$root = dirname(__DIR__);
$autoload = $root . '/api/vendor/autoload.php';
if (!is_file($autoload)) {
    fwrite(STDERR, "Error: composer autoload not found — run: docker compose run --rm php composer install\n");
    exit(1);
}
require $autoload;

use Humanome\Db;
use Humanome\Referentiel\ConflictException;
use Humanome\Referentiel\InvalidDocumentException;
use Humanome\Referentiel\ReferentielRepository;

const RELEASE_NOTE = 'Import initial RESPIRE v7';

$file = $argv[1] ?? $root . '/web/public/data/referentiel/respire-v7.json';

if (!is_file($file)) {
    fwrite(STDERR, "Error: referentiel file not found: {$file}\n");
    fwrite(STDERR, "Regenerate it with: node scripts/extract-referentiel.mjs\n");
    exit(1);
}

if (!Db::isConfigured()) {
    fwrite(STDERR, "Error: DB_HOST is not set (expected DB_HOST/DB_NAME/DB_USER/DB_PASSWORD in env).\n");
    exit(1);
}

try {
    $doc = json_decode((string) file_get_contents($file), true, 512, JSON_THROW_ON_ERROR);
    if (!is_array($doc)) {
        throw new RuntimeException('Top-level JSON value is not an object');
    }

    $repository = new ReferentielRepository(Db::get());
    // importPublishedDocument() validates against the schema, recomputes the
    // content hash and checks it against the declared contentHash field.
    $result = $repository->importPublishedDocument($doc, RELEASE_NOTE);
} catch (InvalidDocumentException $e) {
    fwrite(STDERR, 'Invalid referentiel document: ' . $e->getMessage() . "\n");
    foreach ($e->getErrors() as $pointer => $messages) {
        fwrite(STDERR, sprintf("  %s: %s\n", $pointer, implode(' | ', $messages)));
    }
    exit(1);
} catch (ConflictException $e) {
    fwrite(STDERR, 'Conflict: ' . $e->getMessage() . "\n");
    exit(1);
} catch (Throwable $e) {
    fwrite(STDERR, 'Import failed: ' . $e->getMessage() . "\n");
    exit(1);
}

if ($result['status'] === 'unchanged') {
    printf(
        "already imported — %s %s (hash %s), nothing to do.\n",
        basename($file),
        $result['semver'],
        substr($result['contentHash'], 0, 12),
    );
} else {
    printf(
        "imported %s as published version %s of referentiel \"%s\" (hash %s, release note: %s).\n",
        basename($file),
        $result['semver'],
        ReferentielRepository::DEFAULT_REFERENTIEL_ID,
        substr($result['contentHash'], 0, 12),
        RELEASE_NOTE,
    );
}
exit(0);
